ClubCedille/k8s-cedille-production

- apps/calidum-rotae/prod/ingress.yaml
- apps/wiki-cedille/base/deployment.yaml
- apps/wiki-cedille/base/kustomization.yaml
- apps/wiki-cedille/base/network.yaml
- apps/wiki-cedille/kustomization.yaml
- apps/wiki-cedille/prod/ingress.yaml
- apps/wiki-cedille/prod/kustomization.yaml
- apps/wiki-cedille/wiki-cedille.argoapp.yaml
> wiki cedille

- apps/saveursdegenie/base/deployment.yaml
- apps/saveursdegenie/base/kustomization.yaml
- apps/saveursdegenie/base/network.yaml
- apps/saveursdegenie/prod/ingress.yaml
- apps/saveursdegenie/prod/kustomization.yaml
- apps/saveursdegenie/saveursdegenie.argoapp.yaml
> saveurs de genie

- apps/calidum-rotae/base/calidum-rotae-service/deployment.yaml
- apps/calidum-rotae/base/email-provider/deployment.yaml
- apps/trema/prod/ingress.yaml
> Calidum-rotae fix

- apps/calidum-rotae/base/calidum-rotae-service/deployment.yaml
> fixed coroot port

- apps/calidum-rotae/base/email-provider/deployment.yaml
> added env email variables

- apps/patchets/base/kustomization.yaml
> removed secrets form kustomization

- apps/patchets/base/kustomization.yaml
> removed common labels

- apps/aeroets/grav/aeroets-grav.argoapp.yaml
- apps/aeroets/grav/kustomization.yaml
- apps/aeroets/grav/prod/kustomization.yaml
- bases/grav/deployment.yaml
- bases/grav/kustomization.yaml
- bases/grav/network-policy.yaml
- bases/grav/network.yaml
> aeroets deployment

- apps/patchets/base/deployment.yaml
> removed illegal fields

- apps/patchets/base/kustomization.yaml
> test without helmchart

- apps/patchets/base/kustomization.yaml
> fixed indentation

- apps/patchets/base/kustomization.yaml
> another test

- apps/patchets/base/db/postgres.yaml
- apps/patchets/base/kustomization.yaml
> removed helm postrgres

- apps/patchets/base/db/postgres.yaml
> modified pvc

- apps/patchets/base/db/postgres.yaml
> fixed pg serrvice name

- apps/patchets/base/service.yaml
> fixed services

- apps/acets/grav/acets-grav.argoapp.yaml
- apps/aeroets/grav/aeroets-grav.argoapp.yaml
- apps/raconteurs/grav/prod/kustomization.yaml
- apps/raconteurs/grav/raconteurs-grav.argoapp.yaml
> Raconteurs

- apps/dronolab/webApp/base/deployment.yaml
- apps/dronolab/webApp/base/kustomization.yaml
- apps/dronolab/webApp/base/network.yaml
- apps/dronolab/webApp/dronolab.argoapp.yaml
- apps/dronolab/webApp/prod/ingress.yaml
- apps/dronolab/webApp/prod/kustomization.yaml
> dronolab webapp

- apps/ingenieuses/base/deployment.yaml
- apps/ingenieuses/base/kustomization.yaml
- apps/ingenieuses/base/service.yaml
- apps/ingenieuses/ingenieuses.argoapp.yaml
- apps/ingenieuses/prod/ingress.yaml
- apps/ingenieuses/prod/kustomization.yaml
- [ x] J'ai vérifié que le code fonctionne correctement.
- [ x] J'ai vérifié que le code respecte l'architecture du projet.
> Ingenieuses

- apps/markets/base/backend-deployment.yaml
- apps/markets/base/backend-service.yaml
- apps/markets/base/frontend-deployment.yaml
- apps/markets/base/frontend-service.yaml
- apps/markets/base/kustomization.yaml
- apps/markets/markets.argoapp.yaml
- apps/markets/prod/ingress.yaml
- apps/markets/prod/kustomization.yaml
> adds markets

- apps/trema/base/network.yaml
> add metrics for prometheus client

- apps/trema/base/deployment.yaml
> add prometheus annotations

- apps/conjure/site/base/deployment.yaml
- apps/conjure/site/base/kustomization.yaml
- apps/conjure/site/base/network.yaml
- apps/conjure/site/conjure.argoapp.yaml
- apps/conjure/site/prod/ingress.yaml
- apps/conjure/site/prod/kustomization.yaml
> adds conjure

- apps/wiki-cedille/base/deployment.yaml
- apps/wiki-cedille/base/network.yaml
- apps/wiki-cedille/prod/ingress.yaml
- apps/wiki-cedille/wiki-cedille.argoapp.yaml
> Cedille staging

- apps/wiki-cedille/wiki-cedille.argoapp.yaml
> argoceedeeznuts

- apps/calidum-rotae/base/discord-provider/deployment.yaml
- apps/calidum-rotae/base/email-provider/deployment.yaml
- apps/calidum-rotae/prod/ingress.yaml
- apps/capra/wiki/base/kustomization.yaml
- apps/cedille/base/deployment.yaml
- apps/markets/base/backend-deployment.yaml
- apps/markets/base/frontend-deployment.yaml
- apps/synapsets/base/deployment.yaml
- apps/synapsets/base/network.yaml
- apps/synapsets/prod/ingress.yaml
> markets kubescore

- apps/calidum-rotae/base/email-provider/networkPolicy.yaml
- apps/cedille/base/deployment.yaml
- apps/cedille/base/kustomization.yaml
- apps/integrale/base/deployment.yaml
- apps/markets/base/backend-deployment.yaml
- apps/trema/base/db/deployment.yaml
- apps/trema/base/deployment.yaml
- apps/wiki-cedille/base/deployment.yaml
> fix temp folders

- apps/ingenieuses/prod/ingress.yaml
Adds www.ingenieuses.ca host rule 
> www.ingenieuses.ca

- apps/markets/markets.argoapp.yaml
> Update markets pull credentials for argocd image updater

- apps/ingenieuses/prod/ingress.yaml
> clean up cedille.club ingress

- apps/markets/base/backend-deployment.yaml
- apps/markets/base/kustomization.yaml
- apps/markets/base/postgresql.yaml
- apps/markets/prod/ingress.yaml
Markets needs a postgresql database now instead of sqlite
> update markets with cnpg

- apps/markets/base/backend-deployment.yaml
> adds for migrations
